name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
      AWS_DEFAULT_OUTPUT: json

    defaults:
      run:
        shell: bash
        working-directory: ./tests/basic/

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Plan
      run: terraform plan -no-color > basic_plan_actual.txt

    - name: Expected Hash
      run: echo ${{ hashFiles('**/basic_plan_expected.txt')}}

    - name: Actual Hash
      run: echo ${{ hashFiles('**/basic_plan_actual.txt')}}

    - name: Actual cat
      run: cat basic_plan_actual.txt

    - name: A/B Check
      if: ${{ hashFiles('**/basic_plan_expected.txt') !=  hashFiles('**/basic_plan_actual.txt') }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('Actual and expected outputs are not equivalent!')
